{
 "title": "GSB Dashboard",
 "refresh": "5s",
 "panels": [
  {
   "title": "NGINX - Aktif Bağlantılar",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nginx_connections_active" }
   ]
  },
  {
   "title": "Product Service - Toplam İstek",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"nodejs-backend1\"})"
    }
   ]
  },
  {
   "title": "Order Service - Toplam İstek",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"order_service\"})"
    }
   ]
  },
  {
   "title": "Aktif Instance Sayısı",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(up{job=~\"nodejs-backend1|order_service\"} == 1)"
    }
   ]
  },
  {
   "title": "Product Service - İstek Sayısı (instance bazlı)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_requests_total{job=\"nodejs-backend1\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Order Service - İstek Sayısı (instance bazlı)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_requests_total{job=\"order_service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node.js - Memory (Heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_nodejs_heap_size_used_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node.js - CPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(nodejs_process_cpu_seconds_total[1m]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}